### ISSUE TITLE
AWS spot instances enable by choosing another ami?

### ISSUE THREAD

**Issue by jakovm** [sequenceiq/cloudbreak#1204]
Hi all,

is it possible to change the ami version somewhere in the env settings or in the blueprint, so the requested aws spot instances use another image instead of ami-1edc7d6d? This one doesn't support spot instances. If yes, any suggestions which one to use instead?
Best,
Jakov

**Comment by lalyos** [comment]
Hi Jakov,

You can't really use arbitrary base ami. You need a HDP supported os with docker. Sounds simple, but the fun comes with: which systemd/docker/kernel version and so on.

For licencing issues we cant use CentOS as base (you cant publish images starting from CentOS), so we use RedHat as base. Unfortunately RedHat doesn't supports spot instances ...

The cloudbreak api was supporting spotinstances, but we temporarly removed because of the licencing issue mentioned above... We will think about a workaround for upcoming releases ...

**Comment by jakovm** [comment]
Hi lalyos,

thanks for the quick response. 
I'm a bit confused. Cloudbreak started following ami: cb-centos71-amb212-2015-12-06 (ami-1edc7d6d)
That should be a CentOS image, no?

**Comment by lalyos** [comment]
yes it is confusing indeed. Originally it was based from a centos, but as i mentioned we changed the base to be RedHat. We kept the name, as it was meanr to be a temporary change.
But it wasn't ...

**Comment by jakovm** [comment]
Ok thanks for the clarification!
