### ISSUE TITLE
Is there a way to add volumes to containers ?

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1233]
Hi,

An option to bypass the ``dm.basesize`` (cf #1232) for us would be to attach volumes to running containers. How can we change this options so that it's run automatically ?

Is there another way than to customise your image and use our own docker registry for deployment?  Btw, is it possible to define a custom docker registry ?

Thanks
Nicolas

**Comment by doktoric** [comment]
Hi, 
Attaching volumes to a running container is not solved by docker so it is not supported in cloudbreak.
If you want more space in your container then please add more attached disks to your templates and cloudbreak will attach this disks to the container automatically when the containers starting.
Custom repository also not supported but if you want to customize your docker images then you have to put it on docker hub and then configure cloudbreak to use your docker images (In this case the boot process will much slower because we have to pull these new images).
Br,
R

**Comment by nsteinmetz** [comment]
Ok, thanks !

Now I have a better overview, I can meet the team and see how we'll move on from this information.

**Comment by matyix** [comment]
Hi Nicolas

Can you connect directly with me at jmatyas at hortonworks.com to better understand your needs and how we can help, guide you on the roadmap?

Thanks,
Janos
