### ISSUE TITLE
Sending mail from the sultans container

### ISSUE THREAD

**Issue by gmateesc** [sequenceiq/cloudbreak#1492]
As part of a user registering in the Cloudbreak UI, the sultans container needs to send email to the user. With the current setup, this is cumbersome. 

The Cloudbreak Deployer host (e.g., an AMI instance), let's call it the cbd_host, has postfix configured so emails can be sent from this host. 

However, for the sultans container to send email, it must authenticate with with the SMTP server, and 
SASL needs to be configured for postfix on cbd_host. So additional configuration is required.

Alternatively, if iptables, xinetd or socat were available on the sultans container, one could forward 
localhost:25 to cbd_host:25 and one could send email from the container with the current configuration of cbd_host. Unfortunately, none of these is available in the sultans container.

Can we have some guidence on how to proceed here, or we are missing some configurations which are not covered in documentation .

http://sequenceiq.com/cloudbreak-docs/latest/configuration/#smtp

**Comment by gmateesc** [comment]
I think that I found the cause of the problem and a workaround:

1. Cause
------------

When the environment variables 

    SL_SMTP_SENDER_USERNAME
    SL_SMTP_SENDER_PASSWORD

are defined in the sultans container -- and they are derived 
from the environment variables 

   CLOUDBREAK_SMTP_SENDER_USERNAME
   CLOUDBREAK_SMTP_SENDER_PASSWORD

on the cloudbreak deployer -- even if they are set to the empty string, 
the Javascript code in mailer.js tries to do authentication with the SMTP server.


2. Workaround
-------------------

Make sure that 

    SL_SMTP_SENDER_USERNAME
    SL_SMTP_SENDER_PASSWORD

are not defined in the sultans container.

**Comment by mhmxs** [comment]
Hi @gmateesc,

First of all thank you for the report. Your investigation was correct. We are [looking for null](https://github.com/sequenceiq/cloudbreak/blob/master/auth/mailer.js#L18) instead of empty string.

"Alternatively, if iptables, xinetd or socat were available on the sultans container, one could forward" you could build your own container based on our and use it [here](https://github.com/sequenceiq/cloudbreak-deployer/blob/master/include/cloudbreak.bash#L41) and [here](https://github.com/sequenceiq/cloudbreak-deployer/blob/master/include/cloudbreak.bash#L45).

I checked the workaround on the latest (i don't know which version do you use) and if you delete SL_SMTP_SENDER_USERNAME and it's pair from docker-compose.yml file (as you suggested), next start will fail because the compose file difference. So till we fix the issue and you faced with this, you can use an undocumented export CBD_FORCE_START=true in your Profile. Please keep in mind with this flag the compose file consistency is your responsibility.

**Comment by mhmxs** [comment]
Issue fixed in this commit: https://github.com/sequenceiq/cloudbreak/commit/9f898deb61d0a12594d437a055bcb76826107ba0.
