### ISSUE TITLE
Can't terminate a node with a autoscaling group of [1:1]

### ISSUE THREAD

**Issue by nsteinmetz** [sequenceiq/cloudbreak#1537]
Hi,

We use CB 1.2.1

We had a full system partition on the Client1 machine leading to docker thin-pool being corrupted ; docker system no longer starts; so I wanted to terminate it in order to spawn a new one. However I can't terminate it, I have in logs: 

```
/cbreak_cloudbreak_1 | com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.cloudbreak.service.stack.connector.OperationException: com.amazonaws.AmazonServiceException: AutoScalingGroup integration-108-XXXX has min-size=1, max-size=1, and desired-size=1. To detach 1 instances, please update the AutoScalingGroup sizes appropriately. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: XXXXXXXXXX)
```

Then we went in AWS Console and update the Autoscaling group to {1:2} but without any impacts. I can't sync the cluster as it's in update progress but we know the request will never succeed.

What should I do then ?

Thanks,
Nicolas

**Comment by nsteinmetz** [comment]
I will try a [0:2] with a desire state to 1 to test if it works better this way.

**Comment by biharitomi** [comment]
Hi @nsteinmetz ,

Please correct me if I hasn't understood the case correctly. But I assume that one of your cluster starts failed with the mentioned docker issue on one node. The failed node is related to an autoscaling group which has only one element so I assume that is some kind of master hostgroup.
You tried to terminate the failed instance through the Cloudbreak and got the following exception:
`com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.cloudbreak.service.stack.connector.OperationException: com.amazonaws.AmazonServiceException: AutoScalingGroup integration-108-XXXX has min-size=1, max-size=1, and desired-size=1. To detach 1 instances, please update the AutoScalingGroup sizes appropriately. (Service: AmazonAutoScaling; Status Code: 400; Error Code: ValidationError; Request ID: XXXXXXXXXX)`
If a start of a master hostgroup failed for you then it is now a big problem because Cloudbreak could not be upscale a master hostgroup yet, so a new node could not be added by Cloudbreak. 
I think the best way is to fix the failing node's docker if it is possible. Because Cloudbreak could not spin up a new node in that instance/host/autoscaling group. If you add a new node to that autoscaling group through AWS portal in that case you should update the related part of the Cloudbreak's database manually which is not a trivial task.

Please let us know how you handled or try to handle this issue!

Br,
Tamas

**Comment by nsteinmetz** [comment]
We started from the default template we extended a little bit. The node was fine but some containers fill the root system , and it aims the "client1" group ; not one of the master group.

I could terminate it the VM by faking the database and tell that stack was available. Then I could remove the node as described below:

```
11/05/2016 11:22:43 jcd-smartdata-scalable-integration - available: Synced instance states with the cloud provider
11/05/2016 11:22:45 jcd-smartdata-scalable-integration - available: Cloudbreak cluster state synchronized with Ambari: There are stopped and running Ambari services as well. Restart or stop all of them and try syncing later.
11/05/2016 11:25:34 jcd-smartdata-scalable-integration - update in progress: Removing instance from the infrastructure
11/05/2016 11:25:34 jcd-smartdata-scalable-integration - update in progress: Terminating host: ip-10-235-27-202.node.dc1.consul from host group: host_group_client_1
11/05/2016 11:25:40 jcd-smartdata-scalable-integration - delete failed: Could not delete host i-08a40b80 from Ambari
11/05/2016 11:25:40 jcd-smartdata-scalable-integration - available: Instance removed
11/05/2016 11:27:29 jcd-smartdata-scalable-integration - available: Synced instance states with the cloud provider
11/05/2016 11:27:31 jcd-smartdata-scalable-integration - available: Cloudbreak cluster state synchronized with Ambari: There are stopped and running Ambari services as well. Restart or stop all of them and try syncing later.
11/05/2016 11:41:52 jcd-smartdata-scalable-integration - available: Synced instance states with the cloud provider
11/05/2016 11:41:54 jcd-smartdata-scalable-integration - available: Cloudbreak cluster state synchronized with Ambari: The cluster's state is up to date.
```

But now, when I try to add a node to replace the removed one, it says that node count can't be 2 due to Metrics Collector. Whereas I have no longer a node:

```
postgres=# select * from instancegroup where stack_id=108;
 id  |      groupname      | instancegrouptype | nodecount | stack_id | template_id
-----+---------------------+-------------------+-----------+----------+-------------
 958 | host_group_slave_2  | CORE              |         3 |      108 |          60
 960 | host_group_slave_1  | CORE              |         2 |      108 |          58
 957 | host_group_client_1 | CORE              |         0 |      108 |          59
 956 | cbgateway           | GATEWAY           |         1 |      108 |          59
 959 | host_group_master_3 | CORE              |         1 |      108 |          59
 961 | host_group_master_2 | CORE              |         1 |      108 |          59
 962 | host_group_master_1 | CORE              |         1 |      108 |          59
(7 rows)
```

Any idea ?

**Comment by nsteinmetz** [comment]
From:

```
postgres=# select * from hostgroup;
  id  |        name         | cluster_id | constraint_id
------+---------------------+------------+---------------
  962 | host_group_client_1 |        927 |             5
```

and:

```
postgres=# select * from hostgroup_constraint where id=5;
 id | instancegroup_id | constrainttemplate_id | hostcount
----+------------------+-----------------------+-----------
  5 |              957 |                       |         1
(1 row)
```

Should it be set to ``0`` so that when I add a node it's back to 1 ?

**Comment by nsteinmetz** [comment]
Ops team just told me that desired state was set to 0 ; we set it back to 1, an instance is spawned, let's see if cloudbreak and ambari can integrate it.

**Comment by nsteinmetz** [comment]
We give up, instance did not join cloudbreak nor the cluster. We'll kill it in the next few days and set up a new HDP 2.4 cluster to replace it.

**Comment by biharitomi** [comment]
The problem is that the new instance is created by the autoscaling group and Cloudbreak does not know about it, this way the new node has not been bootstrapped by Cloudbreak so containers has not been started with the appropriate config to be able to join to the existing cluster.
I have not seen similar before but you could upscale that client host group from Cloudbreak. It could help if the validation will allow to upscale it form 0 node at all, but just 2 clicks before terminate the entire cluster.

Thanks,
Tamas
