### ISSUE TITLE
Openstack cannot run Cloudbreak Deployer image

### ISSUE THREAD

**Issue by erwan-rouzel** [sequenceiq/cloudbreak#1564]
Hi,

I am trying to run Cloudbreak on a local Openstack using devstack. The purpose of that is to setup a local development environement for Hadoop that allows to develop using a complete cluster instead of just standalone or pseudo-distributed mode.

For this purpose I created a vagrant file that setup the right devstack environement inside VirtualBox. Everything works fine and I can successfully create instances but when I try to create an instance from the Cloudbreak Deployer image I get an error upon booting telling there is some error with the XFS file system and the instance cannot even go past the grub booting phase.

I have noticed the following article on blog which intends doing what I am trying : http://blog.sequenceiq.com/blog/2015/02/17/openstack-cloudbreak/. But I could not have it work properly either for other reasons as I am not able to even start the vagrant box correctly (I think the issue is due to ansible which I am running from windows and is having strange behaviour). So I am instead sticking with my own vagrant file which is working fine to create the box.

Do you have any idea where it comes from and what could be the solution ? I could deploy successfully a cluster using Cloudbreak on a real Openstack running on bare metal so this issue seems to be specific to devstack over Virtual Box so was thinking maybe it has something to do with QEMU which is used instead of KVM for virtualization.

Best regards,

Erwan Rouzel

**Comment by akanto** [comment]
Hi,

We have tested only with KVM with both real OpenStack and Devstack, but not with QEMU, since the cluster will not be installed with QEMU due to its performance limitation. My guess is that probably in case of QEMU the block devices are named differently: https://github.com/sequenceiq/cloudbreak/blob/master/cloud-openstack/src/main/java/com/sequenceiq/cloudbreak/cloud/openstack/view/CinderVolumeView.java#L7

Kind regards,
Attila
