### ISSUE TITLE
Documentation for shutting down and restarting cloudbreak

### ISSUE THREAD

**Issue by rmelick** [sequenceiq/cloudbreak#1590]
Is there any documentation on the proper process to follow to shutdown the cloudbreak-deployer?  During testing, I am stopping my AWS hadoop clusters every night to save money, and I would like to be able to shutdown the cloudbreak instance as well.

**Comment by mhmxs** [comment]
Hi @rmelick,

Current versions doesn't support "instance termination" because some security stuff don't like IP replacement, and it's hard to maintain running tasks. But if you allocate a fix ip for the instance and it gets the same on restart it becomes possible. `cbd kill` command stops Cloudbreak itself and `cbd start` spins it up. But you have to keep in mind, some cluster operation should fail if you terminate Cloudbreak in the middle of the process. During restart Cloudbreak tries to fix them, but your clusters could became inconsistent.

Cheers,
