### ISSUE TITLE
Cloudbreak build fails on RHEL7.1/PPC64LE and RHEL7.1/x86_64

### ISSUE THREAD

**Issue by anuphalarnkar** [sequenceiq/cloudbreak#2048]
**System:**
OS: RHEL 7.1
Arch: Both x86_64 and PPC64LE

**Commands**
1. git clone https://github.com/sequenceiq/cloudbreak.git
2. cd cloudbreak
3. git checkout 1.10.0-dev.14
4. ./gradlew clean build

**Result 1**:
After issuing above command on both architectures, I was getting an error related to missing references to **consul-api** from **com.sequenceiq** and version **1.10**
I resolved this issue by changing the repo to **com.ecwid.consul** and version to **1.1.10** in **build.gradle** files of modules autoscale, core and integration-test

**Result 2**:
Next, I received error for autoscale module related to missing jar file **ambari-client-2.4.19.jar** 
I checked on sequenceiq repo on github and found the **ambari-rest-client** repo which I cloned and built and the result was a jar file that I exported to CLASSPATH variable
The issue was resolved for autoscale module, but resurfaced for another module **cloud-reactor**

Please check the attached log.

Am I missing something for Ambari client? I would greatly appreciate any inputs from community.

Thanks in advance,
Anup Halarnkar
[cloudbreak-build-failure-log.txt](https://github.com/sequenceiq/cloudbreak/files/589123/cloudbreak-build-failure-log.txt)

**Comment by martonsereg** [comment]
Ambari client and consul client should be downloaded automatically from our own maven repository in S3, it is configured here: https://github.com/sequenceiq/cloudbreak/blob/master/core/build.gradle#L6

e.g.: ambari client jar is available here:
https://s3-eu-west-1.amazonaws.com/maven.sequenceiq.com/releases/com/sequenceiq/ambari-client/2.4.19/ambari-client-2.4.19.jar

please check if you can download this jar, or if your configuration allows pulling jars from this repo.

Marton


On Nov 14, 2016, at 12:55 PM, Anup Halarnkar <notifications@github.com<mailto:notifications@github.com>> wrote:


System:
OS: RHEL 7.1
Arch: Both x86_64 and PPC64LE

Commands

  1.  git clone https://github.com/sequenceiq/cloudbreak.git
  2.  cd cloudbreak
  3.  git checkout 1.10.0-dev.14
  4.  ./gradlew clean build

Result 1:
After issuing above command on both architectures, I was getting an error related to missing references to consul-api from com.sequenceiq and version 1.10
I resolved this issue by changing the repo to com.ecwid.consul and version to 1.1.10 in build.gradle files of modules autoscale, core and integration-test

Result 2:
Next, I received error for autoscale module related to missing jar file ambari-client-2.4.19.jar
I checked on sequenceiq repo on github and found the ambari-rest-client repo which I cloned and built and the result was a jar file that I exported to CLASSPATH variable
The issue was resolved for autoscale module, but resurfaced for another module cloud-reactor

Please check the attached log.

Am I missing something for Ambari client? I would greatly appreciate any inputs from community.

Thanks in advance,
Anup Halarnkar
cloudbreak-build-failure-log.txt<https://github.com/sequenceiq/cloudbreak/files/589123/cloudbreak-build-failure-log.txt>

**Comment by anuphalarnkar** [comment]
I have manually downloaded the jar file. But, it seems I cannot access "maven.sequenceiq.com/releases". As a result, I am still getting the error:
**error: error reading /home/xxxx/.gradle/caches/modules-2/files-2.1/com.sequenceiq/consul-api/1.10/4ab1d4da2db7f16951b3688089374ee9f8c0a56/consul-api-1.10.jar; error in opening zip file**

**Comment by anuphalarnkar** [comment]
Can you share a download link for the consul-api-1.10.jar file?

**Comment by anuphalarnkar** [comment]
One update. I can access the link "maven.sequenceiq.com". I tried this link "http://maven.sequenceiq.com/releases/org/pacesys/openstack4j-parent/2.0.10-siq01/openstack4j-parent-2.0.10-siq01.pom" and it gave me the pom file. 
Looks like only the "consul-api-1.10.jar" file is not getting downloaded by the script.

**Comment by anuphalarnkar** [comment]
[cloudbreak-build-failure-consul-api-log.txt](https://github.com/sequenceiq/cloudbreak/files/591376/cloudbreak-build-failure-consul-api-log.txt)

**Comment by martonsereg** [comment]
consul-api jar is available here:
https://s3-eu-west-1.amazonaws.com/maven.sequenceiq.com/releases/com/sequenceiq/consul-api/1.10/consul-api-1.10.jar

I've double checked the S3 bucket permissions and it is set to "Everyone can open/download". If you're able to download it from this link, then gradle should be able to do the same.

**Comment by anuphalarnkar** [comment]
I am getting a successful build now with "**./gradlew clean build**". I checked the Makefile and saw many commands. So, I ran **make**. But, after successful build, the line containing cbd-test results in error
**ssh: Could not resolve hostname cbd-test: Name or service not known
lost connection
make: *** [dev-deploy] Error 1**

Do I need to make some kind of setup here?
[cloudbreak-build-success-16Nov16.txt](https://github.com/sequenceiq/cloudbreak/files/593781/cloudbreak-build-success-16Nov16.txt)

**Comment by anuphalarnkar** [comment]
Build is also successful for PPC64LE with **./gradlew clean build**. But, fails for **dev-deploy** as reported earlier for **x86_64**
I believe the next step is to use cloudbreak-deployer. So, will start building this...

**Comment by anuphalarnkar** [comment]
Build passes on both ppc and x86. So closing this issue.
