### ISSUE TITLE
Stop cluster function error

### ISSUE THREAD

**Issue by cjcrobin** [sequenceiq/cloudbreak#455]
I use the cloudbreak create a three nodes clusters. And it'is running. Today, after finish the job, I stop the cluster in the cloudbreak hosted dashboard, and few minutes later, it displayed stopped, but the "start" button is missing. And I check in AWS, actually those instances are still running.

**Comment by doktoric** [comment]
In cloudbreak there are two phase of stop:
- The first is when we stopping the cluster so the ambari cluster.
- The second when we stopping the infrastructure layer (the instances on amazon)

When these two phase ended we will display the start button again. Maybe just your ambari cluster stopped because usually the infrastructure stop is a little bit more time :)

**Comment by matyix** [comment]
Fixed.
