### ISSUE TITLE
Exception:Unfortunately the cluster infrastructure could not be stopped

### ISSUE THREAD

**Issue by AliGouta** [sequenceiq/cloudbreak#696]
After creating a cluster on spot instances in amazon (all host-groups are spot instances), then when I stop the cluster I always get this message:

3/6/2015 20:31:32 testspot - stop failed: com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.cloudbreak.core.CloudbreakException: Unfortunately the cluster infrastructure could not be stopped.

Then I can't do anything neither through Ambari (start/stop server) nor through sequenceIQ. The only option would be to terminate the cluster. Any idea ?

**Comment by martonsereg** [comment]
If I'm correct Aws spot instances cannot be stopped. We shouldn't allow it on the UI btw, but it won't work because of the ec2 restriction.

On 3 Jun 2015 8:36 pm, AliGouta <notifications@github.com> wrote:

After creating a cluster on spot instances in amazon (all host-groups are spot instances), then when I stop the cluster I always get this message:

3/6/2015 20:31:32 testspot - stop failed: com.sequenceiq.cloudbreak.core.CloudbreakException: com.sequenceiq.cloudbreak.core.CloudbreakException: Unfortunately the cluster infrastructure could not be stopped.

Then I can't do anything neither through Ambari (start/stop server) nor through sequenceIQ. The only option would be to terminate the cluster. Any idea ?

-

**Comment by AliGouta** [comment]
Indeed, I just checked it! In the next release, it would be intresting if we may stop a host group where we can put reserved instances as master nodes and simply terminate the slave instances that belong to another host-group where we can put spot instances. Thank you.
