### ISSUE TITLE
about cloudbreak  to aws 

### ISSUE THREAD

**Issue by henryon** [sequenceiq/cloudbreak#877]
I've encountered some issues like below, when I want to add crendential to  my account on cloudbreak.

aws credentials  create failed iam role is already in use by a different account

refer link: http://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.3.0/bk_cldbrk_install/bk_cldbrk_instl.pdf

**Comment by martonsereg** [comment]
this is because the IAM role you're trying to setup in the credentials pane is already configured for another cloudbreak account. This is not allowed due to security reasons, so I suggest to create a different IAM role with the same parameters and try to use its arn when setting up your credential.
If you'd like to use the same IAM role with multiple users I suggest to invite the other users to your account and then you can share the cloudbreak resources (like credentials) with them.

**Comment by henryon** [comment]
ok, thanks martonsereg. will try it .

**Comment by henryon** [comment]
it's works fine.
