### ISSUE TITLE
is there any reference for HDP2.2

### ISSUE THREAD

**Issue by henryon** [sequenceiq/cloudbreak#888]
I am searching all over the world. not found the relative documents. so Is there any documents for refer.Then, I can setup HDP2.2 via cloudbreak.

**Comment by matyix** [comment]
Cloudbreak uses Ambari to provision HDP. In order to choose a particular version of HDP you can set that up in the Ambari Blueprint. 

I assume you are familiar with Ambari Blueprints - nevertheless, as you can see in the documentation if you'd like to choose a particular version just use the desired stack version:

```
"Blueprints" : {
    "stack_name" : "HDP",
    "stack_version" : "2.1"
  }

```
Also Cloudbreak can take the RPMs from a custom repository (Advanced options).

https://cwiki.apache.org/confluence/display/AMBARI/Blueprints

https://cwiki.apache.org/confluence/display/AMBARI/Quick+Start+Guide
